---
name: news_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  country_code_picker: ^3.0.0
  geolocator: ^9.0.2
  http: ^0.13.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  fonts:
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Regular.ttf
    - asset: assets/fonts/Roboto-Thin.ttf
      weight: 100
    - asset: assets/fonts/Roboto-Light.ttf
      weight: 300
    - asset: assets/fonts/Roboto-Medium.ttf
      weight: 500
    - asset: assets/fonts/Roboto-Bold.ttf
      weight: 700
    - asset: assets/fonts/Roboto-Black.ttf
      weight: 900
